### ISSUE TITLE
The hotkeys do not work

### ISSUE THREAD

**Issue by javiavid** [bfcs/media-extended#1]
The hotkeys do not work, I have configured one from the obsidian configuration, but when I press it nothing happens.

**Comment by bfcs** [comment]
Hi, same as the commands issue, try to re enter obsidian maybe help

**Comment by javiavid** [comment]
Yes, it was the same problem.

I have seen that when you add several points this happens:
<img width="273" alt="image" src="https://github.com/bfcs/media-extended/assets/7627504/4a8f59be-e2a8-4ed8-a021-41cfc0be3a0e">

<img width="287" alt="image" src="https://github.com/bfcs/media-extended/assets/7627504/fba9949b-2810-4a83-942b-a9d50a971c79">


Maybe it would be good to add an empty line at the end of each capture?

**Comment by bfcs** [comment]
Hi, @javiavid , thanks , in setting panel, add new line to template could solve this, I would update the code to change the default template
<img width="671" alt="image" src="https://github.com/bfcs/media-extended/assets/52602045/cd8d323c-5f89-4e6d-85ba-28ac107ab496">
