### ISSUE TITLE
Capture order

### ISSUE THREAD

**Issue by javiavid** [bfcs/media-extended#11]
When you take several time captures, they are added in reverse, the most recent ones on top.

<img width="520" alt="image" src="https://github.com/bfcs/media-extended/assets/7627504/78f8fdac-67c8-4a8e-8865-225101e8bb05">

**Comment by bfcs** [comment]
Hi, that's because it will insert at the position of current cursor, before you perform insertion, need to place your cursor in the right position.

**Comment by bfcs** [comment]
update code to change the cursor position after insertion
