### ISSUE TITLE
How do I cancel the blurring effect when I pause a video?

### ISSUE THREAD

**Issue by kin30528** [bfcs/media-extended#14]
Thanks for updating media extended and making it better!👍🎉

How do I cancel the blurring effect when I pause to play video? beacuse sometimes I have to look at the screen to take some notes.

**Comment by bfcs** [comment]
Hi, @kin30528 
could you update a screenshot

**Comment by kin30528** [comment]
> 你好， @kin30528 能更新一下截圖嗎
![圖片](https://github.com/bfcs/media-extended/assets/121107652/0aa2bfef-39c7-4243-bad9-7556919f8198)
Thank u ~

**Comment by bfcs** [comment]
Hi, @kin30528 
试试在设置里使用YouTube原生控制面板
<img width="788" alt="image" src="https://github.com/bfcs/media-extended/assets/52602045/1b110800-4dbd-499a-a344-9f8bad447eed">

**Comment by kin30528** [comment]
@bfcs 謝謝，這個問題在更新後就解決了，謝謝你把這個插件更新，並優化的更好，現在很喜歡這個插件
