### ISSUE TITLE
Command palette no options

### ISSUE THREAD

**Issue by javiavid** [bfcs/media-extended#2]
In the command palette, the plugin commands are not displayed.

**Comment by bfcs** [comment]
Hi, I could see the commands, try to reload obsidian?
<img width="702" alt="image" src="https://github.com/bfcs/media-extended/assets/52602045/9894fd1d-1d3a-45c2-8bc8-17f547cab928">

**Comment by javiavid** [comment]
It must have been an error since I had previously installed the media extended and YouTube transcription plugins. Remove them and reboot.
Solved
