### ISSUE TITLE
FR: Timestamp opens in the browser

### ISSUE THREAD

**Issue by javiavid** [bfcs/media-extended#4]
When you select the timestamp from the transcription panel or when dragging to a note it is necessary to change &t to #t. Is it possible to do it automatically?

**Comment by bfcs** [comment]
Hi, re enter obsidian and put the timestamp inside a callout could enable you to navigate the video in live view mode, I already change the & to #, see readme for more information.

<img width="309" alt="image" src="https://github.com/bfcs/media-extended/assets/52602045/b509dbc2-c30c-4595-ad8a-3aa82a6b809a">

<img width="284" alt="image" src="https://github.com/bfcs/media-extended/assets/52602045/5fd1cf5b-a612-4920-8cba-3075969bd8d5">

**Comment by javiavid** [comment]
The callout idea is very good, I meant when you drag a transcript from the panel to the note or when you click on a timestamp in the transcript panel.

**Comment by javiavid** [comment]
It works correctly, it was again a problem of having the old plugins installed. Sorry...
