### ISSUE TITLE
Multiple transcription panels

### ISSUE THREAD

**Issue by javiavid** [bfcs/media-extended#6]
I have seen that in your example you have two transcription panels, I can't reproduce that. I have to close it and load it for the next video to open properly, but I only have one panel at a time.
How is this done?

**Comment by bfcs** [comment]
Hi, each video has only one transcript panel, if you click twice, it will close the panel you've opened before

**Comment by javiavid** [comment]
And once again for the old plugins.. 🙈
If you want, I delete the posts
